### ISSUE TITLE
addons_default.register is not a function

### ISSUE THREAD

**Issue by gelmio** [bbbtech/storybook-formik#62]
I'm getting the following error in the browser console when using storybook-formik v2.5.0 with SB v7:
```
Uncaught TypeError: addons_default.register is not a function
    at node_modules/@bbbtech/storybook-formik/dist/esm/register.js (register.tsx:8:8)
    at __init (register.mjs:8:56)
    at register.js:1:1
```

My SB config is as follows:
```
const config = {
	stories: ["../src/**/*.stories.@(js|jsx|ts|tsx)"],
	addons: [
		"@storybook/addon-links",
		"@storybook/addon-essentials",
		"@storybook/addon-a11y",
		"@bbbtech/storybook-formik/register",
		"@storybook/addon-interactions",
	],
	features: {
		emotionAlias: false,
		interactionsDebugger: true,
	},
	core: {},
	framework: {
		name: "@storybook/react-vite",
		options: {},
	},
};
export default config;
```

**Comment by bhishp** [comment]
as far as I can tell, sb7 is still in alpha? I don't know too much about it but would there be any other changes required to support it? I'd prefer we do this on a branch so we don't break compatibility with sb6
